// This file is auto-generated by @hey-api/openapi-ts

export type Candidate = {
    candidate_first_name: string;
    candidate_last_name: string;
    candidate_desc: string;
    linkedin: string;
    github: string;
    resume: string;
    email: string;
    phone_number: string;
    created_at: string;
    updated_at: string;
    generated_desc: string;
};

export type CandidateCreate = {
    candidate_first_name: string;
    candidate_last_name: string;
    candidate_desc: string;
    linkedin: string;
    github: string;
    resume: string;
    email: string;
    phone_number: string;
    created_at?: string;
    updated_at?: string;
    generated_desc?: string;
};

export type CandidateRole = {
    candidate_id: string;
    candidate_role_status?: (CandidateRoleStatus);
    candidate_role_notes?: (Array<CandidateRoleNote> | null);
    criteria_scores?: (Array<CriteriaScoringItem> | null);
    candidate_role_generated_description?: (string | null);
    created_at: string;
    updated_at: string;
    readonly candidate: (Candidate | null);
};

export type CandidateRoleCreate = {
    candidate_id: string;
    candidate_role_status?: (CandidateRoleStatus);
    candidate_role_notes?: (Array<CandidateRoleNote> | null);
    criteria_scores?: (Array<CriteriaScoringItem> | null);
    candidate_role_generated_description?: (string | null);
    created_at?: string;
    updated_at?: string;
};

export type CandidateRoleNote = {
    type: CandidateRoleNoteType;
    notes: string;
    created_at?: string;
};

export type CandidateRoleNoteType = 'Generated' | 'Takehome Assignment' | 'Email' | 'Phone Screen' | 'Other';

export type CandidateRoleStatus = 'Outreach' | 'Screening' | 'Interview' | 'Offer' | 'Hired' | 'Rejected';

export type CandidateRoleUpdate = {
    candidate_id: string;
    candidate_role_status?: (CandidateRoleStatus);
    candidate_role_notes?: (Array<CandidateRoleNote> | null);
    criteria_scores?: (Array<CriteriaScoringItem> | null);
    candidate_role_generated_description?: (string | null);
    updated_at?: string;
};

export type CandidateUpdate = {
    candidate_first_name: string;
    candidate_last_name: string;
    candidate_desc: string;
    linkedin: string;
    github: string;
    resume: string;
    email: string;
    phone_number: string;
    updated_at?: string;
};

export type CandidateWithId = {
    candidate_first_name: string;
    candidate_last_name: string;
    candidate_desc: string;
    linkedin: string;
    github: string;
    resume: string;
    email: string;
    phone_number: string;
    created_at: string;
    updated_at: string;
    generated_desc: string;
    candidate_id: string;
};

export type Company = {
    company_name: string;
    company_desc: string;
    founders: Array<CompanyFounder>;
    created_at: string;
    updated_at: string;
};

export type CompanyCreate = {
    company_name: string;
    company_desc: string;
    founders: Array<CompanyFounder>;
    created_at?: string;
    updated_at?: string;
};

export type CompanyFounder = {
    founder_name: string;
    founder_role: string;
    founder_email: string;
    founder_phone: string;
    founder_linkedin_url: string;
};

export type CompanyUpdate = {
    company_name: string;
    company_desc: string;
    founders: Array<CompanyFounder>;
    updated_at?: string;
};

export type CompanyWithId = {
    company_name: string;
    company_desc: string;
    founders: Array<CompanyFounder>;
    created_at: string;
    updated_at: string;
    company_id: string;
};

export type CriteriaScoringItem = {
    criteria_name: string;
    score: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Role = {
    role_name: string;
    role_desc: string;
    role_requirements?: (string | null);
    role_status?: (RoleStatus);
    role_criteria?: Array<RoleCriteria>;
    created_at: string;
    updated_at: string;
};

export type RoleCreate = {
    role_name: string;
    role_desc: string;
    role_requirements?: (string | null);
    role_status?: (RoleStatus);
    role_criteria?: Array<RoleCriteria>;
    created_at?: string;
    updated_at?: string;
    is_open?: boolean;
};

export type RoleCriteria = {
    criteria_name: string;
};

export type RoleStatus = 'Open' | 'In Review' | 'Closed Filled' | 'Closed Unfilled' | 'Closed Cancelled';

export type RoleUpdate = {
    role_name: string;
    role_desc: string;
    role_requirements?: (string | null);
    role_status?: (RoleStatus);
    role_criteria?: Array<RoleCriteria>;
    updated_at?: string;
};

export type RoleWithId = {
    role_name: string;
    role_desc: string;
    role_requirements?: (string | null);
    role_status?: (RoleStatus);
    role_criteria?: Array<RoleCriteria>;
    created_at: string;
    updated_at: string;
    role_id: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HealthcheckHealthcheckGetResponse = ({
    [key: string]: unknown;
});

export type ListCompaniesCompaniesGetResponse = (Array<CompanyWithId>);

export type CreateCompanyCompaniesPostData = {
    requestBody: CompanyCreate;
};

export type CreateCompanyCompaniesPostResponse = (string);

export type GetCompanyCompaniesCompanyIdGetData = {
    companyId: string;
};

export type GetCompanyCompaniesCompanyIdGetResponse = ((Company | null));

export type UpdateCompanyCompaniesCompanyIdPutData = {
    companyId: string;
    requestBody: CompanyUpdate;
};

export type UpdateCompanyCompaniesCompanyIdPutResponse = (Company);

export type DeleteCompanyCompaniesCompanyIdDeleteData = {
    companyId: string;
};

export type DeleteCompanyCompaniesCompanyIdDeleteResponse = (Company);

export type CreateRoleCompaniesCompanyIdRolesPostData = {
    companyId: string;
    requestBody: RoleCreate;
};

export type CreateRoleCompaniesCompanyIdRolesPostResponse = (string);

export type ListRolesCompaniesCompanyIdRolesGetData = {
    companyId: string;
};

export type ListRolesCompaniesCompanyIdRolesGetResponse = (Array<RoleWithId>);

export type GetRoleCompaniesCompanyIdRolesRoleIdGetData = {
    companyId: string;
    roleId: string;
};

export type GetRoleCompaniesCompanyIdRolesRoleIdGetResponse = ((Role | null));

export type UpdateRoleCompaniesCompanyIdRolesRoleIdPutData = {
    companyId: string;
    requestBody: RoleUpdate;
    roleId: string;
};

export type UpdateRoleCompaniesCompanyIdRolesRoleIdPutResponse = ((Role | null));

export type DeleteRoleCompaniesCompanyIdRolesRoleIdDeleteData = {
    companyId: string;
    roleId: string;
};

export type DeleteRoleCompaniesCompanyIdRolesRoleIdDeleteResponse = (Role);

export type GenerateCriteriaCompaniesCompanyIdRolesRoleIdGenerateCriteriaPostData = {
    companyId: string;
    roleId: string;
};

export type GenerateCriteriaCompaniesCompanyIdRolesRoleIdGenerateCriteriaPostResponse = (Array<RoleCriteria>);

export type CreateCandidateCompaniesCompanyIdRolesRoleIdCandidatesCreatePostData = {
    companyId: string;
    requestBody: CandidateCreate;
    roleId: string;
};

export type CreateCandidateCompaniesCompanyIdRolesRoleIdCandidatesCreatePostResponse = (CandidateRole);

export type AddCandidateCompaniesCompanyIdRolesRoleIdCandidatesPostData = {
    companyId: string;
    requestBody: CandidateRoleCreate;
    roleId: string;
};

export type AddCandidateCompaniesCompanyIdRolesRoleIdCandidatesPostResponse = ((CandidateRole | null));

export type ListCandidatesCompaniesCompanyIdRolesRoleIdCandidatesGetData = {
    companyId: string;
    roleId: string;
};

export type ListCandidatesCompaniesCompanyIdRolesRoleIdCandidatesGetResponse = (Array<CandidateRole>);

export type UpdateCandidateCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdPutData = {
    candidateId: string;
    companyId: string;
    requestBody: CandidateRoleUpdate;
    roleId: string;
};

export type UpdateCandidateCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdPutResponse = ((CandidateRole | null));

export type GetCandidateCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdGetData = {
    candidateId: string;
    companyId: string;
    roleId: string;
};

export type GetCandidateCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdGetResponse = ((CandidateRole | null));

export type DeleteCandidateCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdDeleteData = {
    candidateId: string;
    companyId: string;
    roleId: string;
};

export type DeleteCandidateCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdDeleteResponse = (CandidateRole);

export type GenerateCandidateRoleDescriptionCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdGenerateDescriptionPostData = {
    candidateId: string;
    companyId: string;
    roleId: string;
};

export type GenerateCandidateRoleDescriptionCompaniesCompanyIdRolesRoleIdCandidatesCandidateIdGenerateDescriptionPostResponse = ((string | null));

export type ListCandidatesCandidatesGetResponse = (Array<CandidateWithId>);

export type CreateCandidateCandidatesPostData = {
    requestBody: CandidateCreate;
};

export type CreateCandidateCandidatesPostResponse = (string);

export type GetCandidateCandidatesCandidateIdGetData = {
    candidateId: string;
};

export type GetCandidateCandidatesCandidateIdGetResponse = ((Candidate | null));

export type UpdateCandidateCandidatesCandidateIdPutData = {
    candidateId: string;
    requestBody: CandidateUpdate;
};

export type UpdateCandidateCandidatesCandidateIdPutResponse = (Candidate);

export type DeleteCandidateCandidatesCandidateIdDeleteData = {
    candidateId: string;
};

export type DeleteCandidateCandidatesCandidateIdDeleteResponse = (Candidate);